import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ width: "100%", height: "100%" }}
        className={`antialiased`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#0070f3",
              colorBgContainer: "#f0f2f5",
              colorBorder: "#d9d9d9",
              borderRadius: 4,
            },
          }}
        >
          <AntdRegistry>{children}</AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
